//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandPromptHereGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandPromptHereGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &amp;Prompt Here.
        /// </summary>
        public static string CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        public static string CmdStrategy_Name {
            get {
                return ResourceManager.GetString("CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;
        ///; {1} PowerToy
        ///;
        ///; Generated by Command Prompt Here Generator - Travis Illig
        ///; http://www.paraesthesia.com
        ///;
        ///; Template adapted from original &quot;CMD Prompt Here&quot; PowerToy
        ///; and Visual Studio prompt adaptations from Scott Hanselman
        ///; http://www.computerzen.com
        ///;
        ///
        ///[version]
        ///signature=&quot;$CHICAGO$&quot;
        ///
        ///[DefaultInstall]
        ///CopyFiles = CurrentInstaller.Files.Inf
        ///AddReg    = CurrentInstaller.Reg.Add
        ///
        ///[DefaultUnInstall]
        ///DelFiles  = CurrentInstaller.Files.Inf
        ///DelReg    = CurrentInstaller.Reg.Add,Current [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfTemplate {
            get {
                return ResourceManager.GetString("InfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po&amp;werShell Prompt Here.
        /// </summary>
        public static string PowerShellStrategy_Accelerator {
            get {
                return ResourceManager.GetString("PowerShellStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Prompt.
        /// </summary>
        public static string PowerShellStrategy_Name {
            get {
                return ResourceManager.GetString("PowerShellStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 200&amp;3 Prompt Here.
        /// </summary>
        public static string VS2003CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2003CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2003 Command Prompt.
        /// </summary>
        public static string VS2003CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2003CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 200&amp;5 Prompt Here.
        /// </summary>
        public static string VS2005CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2005CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2005 Command Prompt.
        /// </summary>
        public static string VS2005CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2005CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 200&amp;8 Prompt Here.
        /// </summary>
        public static string VS2008CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2008CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2008 Command Prompt.
        /// </summary>
        public static string VS2008CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2008CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2010 X&amp;64 Prompt Here.
        /// </summary>
        public static string VS2010X64CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2010X64CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2010 (x64) Command Prompt.
        /// </summary>
        public static string VS2010X64CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2010X64CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2010 X&amp;86 Prompt Here.
        /// </summary>
        public static string VS2010X86CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2010X86CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2010 (x86) Command Prompt.
        /// </summary>
        public static string VS2010X86CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2010X86CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2012 &amp;Dev Prompt Here.
        /// </summary>
        public static string VS2012DevCmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2012DevCmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2012 Developer Command Prompt.
        /// </summary>
        public static string VS2012DevCmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2012DevCmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2012 X6&amp;4 Command Prompt.
        /// </summary>
        public static string VS2012NativeX64CmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2012NativeX64CmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2012 Native x64 Command Prompt.
        /// </summary>
        public static string VS2012NativeX64CmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2012NativeX64CmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2013 &amp;Dev Prompt Here.
        /// </summary>
        public static string VS2013DevCmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2013DevCmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2013 Developer Command Prompt.
        /// </summary>
        public static string VS2013DevCmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2013DevCmdStrategy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2015 &amp;Dev Prompt Here.
        /// </summary>
        public static string VS2015DevCmdStrategy_Accelerator {
            get {
                return ResourceManager.GetString("VS2015DevCmdStrategy_Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS 2015 Developer Command Prompt.
        /// </summary>
        public static string VS2015DevCmdStrategy_Name {
            get {
                return ResourceManager.GetString("VS2015DevCmdStrategy_Name", resourceCulture);
            }
        }
    }
}
